apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-j2jd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-j2jd
    app.kubernetes.io/part-of: tkrw-pr712-0075-0067-app
  name: devfile-sample-j2jd
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-j2jd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-j2jd
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0067-tenant/tkrw-pr712-0075-0067-app/devfile-sample-j2jd@sha256:b6db08442f0ab6d1e4131225980802aa3e7883291fd4407186faf7ca942df4a3
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
